### ISSUE TITLE
AutoDock Vina installation in a Conda environment: "pip install vina" fails

### ISSUE THREAD

**Issue by rczerminski-valo** [ccsb-scripps/AutoDock-Vina#101]
Step `pip install vina` fails. It seems that the problem might be with missing swig:

`FileNotFoundError: [Errno 2] No such file or directory: 'swig'`

Here is the full error log:

```
Collecting vina
  Using cached vina-1.2.3.tar.gz (95 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: numpy>=1.18 in ./miniconda3/envs/vina/lib/python3.10/site-packages (from vina) (1.22.3)
Building wheels for collected packages: vina
  Building wheel for vina (pyproject.toml): started
  Building wheel for vina (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for vina (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [103 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Version found 1.2.3 (from __init__.py)
      running bdist_wheel
      running build
      running build_ext
      Boost library location automatically determined in this conda environment.
      Boost library location was automatically guessed at /home/rczerminski/miniconda3/envs/vina/include.
      - include_dirs: ['/home/rczerminski/miniconda3/envs/vina/include/python3.10', '/home/rczerminski/miniconda3/envs/vina/include', 'src/lib']
      - library_dirs: ['/home/rczerminski/miniconda3/envs/vina/lib']
      - swig options: ['-c++', '-small', '-naturalvar', '-fastdispatch', '-shadow', '-py3', '-I/home/rczerminski/miniconda3/envs/vina/include/python3.10', '-I/home/rczerminski/miniconda3/envs/vina/include', '-Isrc/lib']
      - libraries: []
      - extra link args: ['-lboost_thread', '-lboost_serialization', '-lboost_filesystem', '-lboost_program_options']
      Warning: compiler flag -Wstrict-prototypes is not present, cannot remove it.
      - compiler options: ['g++', '-pthread', '-shared', '-B', '/home/rczerminski/miniconda3/envs/vina/compiler_compat', '-Wno-unused-result', '-Wsign-compare', '-DNDEBUG', '-fwrapv', '-O2', '-fPIC', '-O2', '-isystem', '/home/rczerminski/miniconda3/envs/vina/include', '-fPIC', '-O2', '-isystem', '/home/rczerminski/miniconda3/envs/vina/include', '-fPIC', '-std=c++11', '-Wno-long-long', '-pedantic', '-DBOOST_ERROR_CODE_HEADER_ONLY']
      building 'vina._vina_wrapper' extension
      swigging vina/autodock_vina.i to vina/autodock_vina_wrap.cpp
      swig -python -c++ -small -naturalvar -fastdispatch -shadow -py3 -I/home/rczerminski/miniconda3/envs/vina/include/python3.10 -I/home/rczerminski/miniconda3/envs/vina/include -Isrc/lib -o vina/autodock_vina_wrap.cpp vina/autodock_vina.i
      Traceback (most recent call last):
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/_distutils/spawn.py", line 56, in spawn
          proc = subprocess.Popen(cmd, env=env)
        File "/home/rczerminski/miniconda3/envs/vina/lib/python3.10/subprocess.py", line 966, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "/home/rczerminski/miniconda3/envs/vina/lib/python3.10/subprocess.py", line 1842, in _execute_child
          raise child_exception_type(errno_num, err_msg, err_filename)
      FileNotFoundError: [Errno 2] No such file or directory: 'swig'
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "setup.py", line 273, in swig_sources
          return build_ext.swig_sources(self, sources, extension)
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 611, in swig_sources
          self.spawn(swig_cmd + ["-o", target, source])
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 365, in spawn
          spawn(cmd, search_path, dry_run=self.dry_run)
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/_distutils/spawn.py", line 62, in spawn
          raise DistutilsExecError(
      distutils.errors.DistutilsExecError: command 'swig' failed: No such file or directory
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/rczerminski/miniconda3/envs/vina/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "/home/rczerminski/miniconda3/envs/vina/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/rczerminski/miniconda3/envs/vina/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 244, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 174, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 346, in <module>
          setup(
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "setup.py", line 196, in run
          self.run_command('build_ext')
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1214, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "setup.py", line 319, in build_extensions
          build_ext.build_extensions(self)
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 506, in build_extension
          sources = self.swig_sources(sources, ext)
        File "setup.py", line 278, in swig_sources
          '  python setup.py build_ext -I{} -L{}'.format(self.include_dirs, self.library_dir),
        File "/tmp/pip-build-env-pwyxiwr9/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 103, in __getattr__
          raise AttributeError(attr)
      AttributeError: library_dir. Did you mean: 'library_dirs'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vina
Failed to build vina
ERROR: Could not build wheels for vina, which is required to install pyproject.toml-based projects
```

**Comment by diogomart** [comment]
You can install swig in the desired conda environment with
```conda install -c conda-forge swig```
