### ISSUE TITLE
Get error while opening protein files

### ISSUE THREAD

**Issue by MrDizzy13** [ccsb-scripps/AutoDock-Vina#141]
Hi,
When I try to open a protein file, I get this error popping up in the python shell:
ERROR ***************
Traceback (most recent call last):
  File "D:\Program Files (x86)\MGLTools-1.5.7\lib\site-packages\ViewerFramework\VF.py", line 941, in tryto
    result = command( *args, **kw )
  File "D:\Program Files (x86)\MGLTools-1.5.7\lib\site-packages\Pmv\fileCommands.py", line 810, in doit
    newparser = PdbParser(filename,modelsAs=modelsAs)
  File "D:\Program Files (x86)\MGLTools-1.5.7\lib\site-packages\MolKit\pdbParser.py", line 105, in _init_
    MoleculeParser._init_(self, filename, allLines)
  File "D:\Program Files (x86)\MGLTools-1.5.7\lib\site-packages\MolKit\moleculeParser.py", line 36, in _init_
    self.filename = str(filename)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 3-8: ordinal not in range(128)
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Program Files (x86)\MGLTools-1.5.7\lib\lib-tk\Tkinter.py", line 1410, in _call_
    return self.func(*args)
  File "D:\Program Files (x86)\MGLTools-1.5.7\lib\site-packages\Pmv\fileCommands.py", line 614, in guiCallback
    mols.data.extend(mol.data)
AttributeError: 'str' object has no attribute 'data'.
I have the latest version of python installed on my pc.

**Comment by diogomart** [comment]
Hi, this is a MGLTools issue, not Vina, you could try the [mailing list](https://autodocksuite.scripps.edu/support/). In any case, you could try the approach described in the [docs](https://autodock-vina.readthedocs.io/en/latest/).

**Comment by MrDizzy13** [comment]
> Hi, this is a MGLTools issue, not Vina, you could try the [mailing list](https://autodocksuite.scripps.edu/support/). In any case, you could try the approach described in the [docs](https://autodock-vina.readthedocs.io/en/latest/).

Hi sir; thanks for your response. 🙏

**Comment by MrDizzy13** [comment]
> Hi, this is a MGLTools issue, not Vina, you could try the [mailing list](https://autodocksuite.scripps.edu/support/). In any case, you could try the approach described in the [docs](https://autodock-vina.readthedocs.io/en/latest/).

Hi sir. I installed MGLTools v 1.5.6 instead of v 1.5.7, and the problem got solved. Thanks for your advice.

**Comment by diogomart** [comment]
That's good news, thank you for reporting it.
