### ISSUE TITLE
Meeko ligand conversion mistake? 

### ISSUE THREAD

**Issue by akshat998** [ccsb-scripps/AutoDock-Vina#154]
Hello, 

I am trying to run the following: 
`mk_prepare_ligand.py -i ./files/ligand.sdf -o ligand.pdbqt
`
I seem to be getting the error: 
```
/home/akshat/miniconda3/envs/spyder-env/lib/python3.9/site-packages/meeko/preparation.py:109: RuntimeWarning: Skipping mol (name=778): has implicit hydrogens
  warnings.warn("Skipping mol (name=%s): has implicit hydrogens" % name, RuntimeWarning)
Traceback (most recent call last):
  File "/home/akshat/miniconda3/envs/spyder-env/bin/mk_prepare_ligand.py", line 303, in <module>
    pdbqt_string = preparator.write_pdbqt_string()
  File "/home/akshat/miniconda3/envs/spyder-env/lib/python3.9/site-packages/meeko/preparation.py", line 205, in write_pdbqt_string
    raise RuntimeError("Molecule not OK, refusing to write PDBQT\n\nLOG:\n%s" % self.log)
RuntimeError: Molecule not OK, refusing to write PDBQT

LOG:
molecule has implicit hydrogens
```

**Comment by akshat998** [comment]
The ligand file is attached below. Thank you for your help! :) 
```
778
  ModelServer 0.9.6

 29 32  0  0  1  0  0  0  0  0  0
   18.5610  135.2050   -0.0600 N   0  0  0  0  0  0  0  0  0  0  0  0
   17.2650  135.6440    0.4650 C   0  0  0  0  0  0  0  0  0  0  0  0
   19.7520  135.2070    0.7900 C   0  0  0  0  0  0  0  0  0  0  0  0
   18.9500  135.8920   -1.2990 C   0  0  0  0  0  0  0  0  0  0  0  0
   16.3280  135.0430   -0.5960 C   0  0  0  0  0  0  0  0  0  0  0  0
   19.5950  134.1260    1.8570 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.8720  135.6640   -2.4020 C   0  0  0  0  0  0  0  0  0  0  0  0
   16.5930  135.2440   -2.0230 N   0  0  0  0  0  0  0  0  0  0  0  0
   20.1020  132.8670    1.7040 N   0  0  0  0  0  0  0  0  0  0  0  0
   18.9610  134.2450    3.0400 C   0  0  0  0  0  0  0  0  0  0  0  0
   18.1540  135.8470   -3.5710 O   0  0  0  0  0  0  0  0  0  0  0  0
   15.5650  135.0040   -2.9070 C   0  0  0  0  0  0  0  0  0  0  0  0
   20.8650  132.3200    0.5570 C   0  0  0  0  0  0  0  0  0  0  0  0
   19.8100  132.1530    2.7740 C   0  0  0  0  0  0  0  0  0  0  0  0
   19.0960  132.9550    3.6550 N   0  0  0  0  0  0  0  0  0  0  0  0
   15.0300  133.7270   -2.8320 C   0  0  0  0  0  0  0  0  0  0  0  0
   15.0300  135.9470   -3.8520 C   0  0  0  0  0  0  0  0  0  0  0  0
   20.0510  132.2060   -0.7400 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.9770  133.3250   -3.6540 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.9670  135.5450   -4.6930 C   0  0  0  0  0  0  0  0  0  0  0  0
   20.6160  132.5930   -1.9770 C   0  0  0  0  0  0  0  0  0  0  0  0
   18.7370  131.7180   -0.7350 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.4400  134.2320   -4.5910 C   0  0  0  0  0  0  0  0  0  0  0  0
   13.3840  131.7160   -3.4630 Cl  0  0  0  0  0  0  0  0  0  0  0  0
   19.8810  132.4840   -3.1800 C   0  0  0  0  0  0  0  0  0  0  0  0
   18.0080  131.6100   -1.9240 C   0  0  0  0  0  0  0  0  0  0  0  0
   18.5870  131.9950   -3.1560 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.8950  131.8790   -4.2840 C   0  0  0  0  0  0  0  0  0  0  0  0
   17.2860  131.7730   -5.2800 N   0  0  0  0  0  0  0  0  0  0  0  0
  1  2  1  0  0  0  0
  1  3  1  0  0  0  0
  1  4  1  0  0  0  0
  2  5  1  0  0  0  0
  3  6  1  0  0  0  0
  4  7  1  0  0  0  0
  5  8  1  0  0  0  0
  6  9  1  0  0  0  0
  6 10  2  0  0  0  0
  7  8  1  0  0  0  0
  7 11  2  0  0  0  0
  8 12  1  0  0  0  0
  9 13  1  0  0  0  0
  9 14  1  0  0  0  0
 10 15  1  0  0  0  0
 12 16  2  0  0  0  0
 12 17  1  0  0  0  0
 13 18  1  0  0  0  0
 14 15  2  0  0  0  0
 16 19  1  0  0  0  0
 17 20  2  0  0  0  0
 18 21  2  0  0  0  0
 18 22  1  0  0  0  0
 19 23  2  0  0  0  0
 19 24  1  0  0  0  0
 20 23  1  0  0  0  0
 21 25  1  0  0  0  0
 22 26  2  0  0  0  0
 25 27  2  0  0  0  0
 26 27  1  0  0  0  0
 27 28  1  0  0  0  0
 28 29  3  0  0  0  0
M  END
> <model_server_result.job_id>
w4AEw7ZQwrwZw6xbEVEzwp

> <model_server_result.datetime_utc>
2021-02-11 18:48:10

> <model_server_result.server_version>
0.9.6

> <model_server_result.query_name>
ligand

> <model_server_result.source_id>
pdb-bcif

> <model_server_result.entry_id>
1s63

> <model_server_params.name>
atom_site

> <model_server_params.value>
{"label_asym_id":"F","auth_seq_id":3012}

> <model_server_stats.io_time_ms>
3

> <model_server_stats.parse_time_ms>
28

> <model_server_stats.create_model_time_ms>
8

> <model_server_stats.query_time_ms>
193

> <model_server_stats.encode_time_ms>
0

> <model_server_stats.element_count>
29

$$$$
```

**Comment by diogomart** [comment]
Meeko requires explicit hydrogens.
See https://github.com/ccsb-scripps/AutoDock-Vina/issues/153

**Comment by akshat998** [comment]
Thank you so much, 

this worked perfectly! I am closing the issue :)
