### ISSUE TITLE
Error in Macromolecule selection

### ISSUE THREAD

**Issue by MrDizzy13** [ccsb-scripps/AutoDock-Vina#155]
Hi,
when I want to select my protein as a Macromolecule I get this error in the python shell:
charges on carbons unchanged 
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files (x86)\MGLTools-1.5.6\lib\lib-tk\Tkinter.py", line 1403, in __call__
    return self.func(*args)
  File "C:\Program Files (x86)\MGLTools-1.5.6\lib\site-packages\AutoDockTools\autogpfCommands.py", line 4479, in chooseMolecule_cb
    mol = self.chooser.getMolSet()
  File "C:\Program Files (x86)\MGLTools-1.5.6\lib\site-packages\Pmv\guiTools.py", line 178, in getMolSet
    if self.mode=='single': return mols[0]
  File "C:\Program Files (x86)\MGLTools-1.5.6\lib\UserList.py", line 28, in __getitem__
    def __getitem__(self, i): return self.data[i]
IndexError: list index out of range.
the first line is blue and the other lines are red. 
please help me.

**Comment by MrDizzy13** [comment]
and now I got this error:
polar hydrogens missing from n-terminus of chain A
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files (x86)\MGLTools-1.5.6\lib\lib-tk\Tkinter.py", line 1403, in __call__
    return self.func(*args)
  File "C:\Program Files (x86)\MGLTools-1.5.6\lib\site-packages\AutoDockTools\autogpfCommands.py", line 4479, in chooseMolecule_cb
    mol = self.chooser.getMolSet()
  File "C:\Program Files (x86)\MGLTools-1.5.6\lib\site-packages\Pmv\guiTools.py", line 178, in getMolSet
    if self.mode=='single': return mols[0]
  File "C:\Program Files (x86)\MGLTools-1.5.6\lib\UserList.py", line 28, in __getitem__
    def __getitem__(self, i): return self.data[i]
IndexError: list index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files (x86)\MGLTools-1.5.6\lib\lib-tk\Tkinter.py", line 1403, in __call__
    return self.func(*args)
  File "C:\Program Files (x86)\MGLTools-1.5.6\lib\site-packages\AutoDockTools\autogpfCommands.py", line 4479, in chooseMolecule_cb
    mol = self.chooser.getMolSet()
  File "C:\Program Files (x86)\MGLTools-1.5.6\lib\site-packages\Pmv\guiTools.py", line 178, in getMolSet
    if self.mode=='single': return mols[0]
  File "C:\Program Files (x86)\MGLTools-1.5.6\lib\UserList.py", line 28, in __getitem__
    def __getitem__(self, i): return self.data[i]
IndexError: list index out of range.
the first line is blue and the other lines are red.

**Comment by diogomart** [comment]
Hi, if no one can help you here, you could try the [autodock mailing list](https://autodocksuite.scripps.edu/support/).

**Comment by MrDizzy13** [comment]
Thanks
