### ISSUE TITLE
Unable to install autodock

### ISSUE THREAD

**Issue by Lancespace** [ccsb-scripps/AutoDock-Vina#230]
Hey guys, 

First of all I'm sorry. Because I'm literally new to all this and I'm struggling a lot to install the program.

After a couple of days with PyMol I finally got it to run using miniconda and with some troubleshooting from some people which I'm really grateful about. Now the time to get autodock running has come and again the nighmate has begun.

I firstly tried to install via conda, but it can't find the packages. Then I tried this:

```
$ conda create -n vina python=3
$ conda activate vina
$ conda config --env --add channels conda-forge
$ conda install -c conda-forge numpy swig boost-cpp sphinx sphinx_rtd_theme
$ pip install vina
```
But pip install vina say this:
```
Collecting vina
  Using cached vina-1.2.5.tar.gz (89 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [62 lines of output]
      Version found 1.2.5 (from __init__.py)
      running egg_info
      creating vina.egg-info
      writing vina.egg-info\PKG-INFO
      writing dependency_links to vina.egg-info\dependency_links.txt
      writing requirements to vina.egg-info\requires.txt
      writing top-level names to vina.egg-info\top_level.txt
      writing manifest file 'vina.egg-info\SOURCES.txt'
      Boost library is not installed in this conda environment.
      Traceback (most recent call last):
        File "C:\Users\User\miniconda3\envs\vina\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\User\miniconda3\envs\vina\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\miniconda3\envs\vina\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8xx5u5d6\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8xx5u5d6\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8xx5u5d6\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 346, in <module>
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8xx5u5d6\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8xx5u5d6\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8xx5u5d6\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8xx5u5d6\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8xx5u5d6\overlay\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
          super().run_command(command)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8xx5u5d6\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8xx5u5d6\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 314, in run
          self.find_sources()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8xx5u5d6\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 322, in find_sources
          mm.run()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8xx5u5d6\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 551, in run
          self.add_defaults()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8xx5u5d6\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8xx5u5d6\overlay\Lib\site-packages\setuptools\command\sdist.py", line 104, in add_defaults
          super().add_defaults()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8xx5u5d6\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8xx5u5d6\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 335, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8xx5u5d6\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-8xx5u5d6\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "<string>", line 247, in finalize_options
      ValueError: Boost library location was not found!
      Directories searched: conda env, /usr/local/include and /usr/include.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Then, I made it to this webpage and I found executables for windows and I was so happy. But after downloading the executable vina_1.2.5_win.exe it just wouldnt work. I tried to execute it as administrator and window will just open and close ultra fast and nothing else happens. I'm starting to get desperate here.

Can anyone please lend me a hand? For dummies, I have really no idea about how this works.

Thank you very much in adance.

**Comment by rwxayheee** [comment]
Hi @Lancespace, 
On the executable, vina itself doesn't have a graphical interface. You might need to execute it in command prompt. 

>       ValueError: Boost library location was not found!

You might have boost and its library in your conda environment at C:\Users\User\miniconda3\envs\vina\**Lib**. The locate_boost function in [setup.py](https://github.com/ccsb-scripps/AutoDock-Vina/blob/8604f73bf1f29b6f1ef4c4cdbbca0068e99d74fc/build/python/setup.py#L99) didn't see the library likely because it tried to find libraries at C:\Users\User\miniconda3\envs\vina\**lib**.

**Comment by Lancespace** [comment]
> 

Thank you so much for your kind answer.

Could you please indicate me how to solve that issue? I'm completely new in this, for me is like a complete new languague and I  literally don't understand what you are talking about.

Thank you very much.

**Comment by rwxayheee** [comment]
Hi @Lancespace!
If you are planning to use the executable for your docking task on Windows, watching some tutorial videos could be helpful to get you started. For example: https://www.youtube.com/watch?v=-GVZP0X0Tg8
(and here is a more recent one) https://www.youtube.com/watch?v=gnmZYEtv4os
If you wish to use vina as part of a python code, you will need to install via conda or pip. Otherwise, you are ready to dock with just the executable.

**Comment by Lancespace** [comment]
> Hi @Lancespace! If you are planning to use the executable for your docking task on Windows, watching some tutorial videos could be helpful to get you started. For example: https://www.youtube.com/watch?v=-GVZP0X0Tg8 (and here is a more recent one) https://www.youtube.com/watch?v=gnmZYEtv4os If you wish to use vina as part of a python code, you will need to install via conda or pip. Otherwise, you are ready to dock with just the executable.

Hi man, thank you so much.

I know how to dock, what I can't is installing the program. I downloaded the executable but nothing happens. After double clicking in  it, it wouldn't start. A windown appears and disappears in flash, full stop.

I have miniconda also but when I put the commands for installing it (refer to my first post in this same issue) an error occurrs and I'm also unable to install it :( 

Any help would be really appreciated. I'm sure that I'm doing something wrong, I just don't know what.

**Comment by rwxayheee** [comment]
Hi @Lancespace, 

> After double clicking in it, it wouldn't start. A window appears and disappears in flash, full stop.

Vina doesn't have a graphical interface (It will not have a window open to accept inputs). What you see is the expected behavior for such program when double clicking it. 

Could you try to execute it in the command prompt, as showed in the tutorial video? If you have some tools to prepare your ligand and receptor files, the executable is all you need to dock.

**Comment by sherryliu987** [comment]
If you're struggling use AutoDock locally, feel free to try https://www.tamarind.bio/autodock-vina, a website which offers a no-code interface for bioinformatics tools including AutoDock for free.

**Comment by rwxayheee** [comment]
This was a pip install problem (reported in other issues). Added to Maintenance Release.
