### ISSUE TITLE
ADFR Fail to generate PDBQT for a protein.pdb

### ISSUE THREAD

**Issue by Kerro-junior** [ccsb-scripps/AutoDock-Vina#241]
When I use ADFR to process pocket.pdb of PDBbind dataset, there are four pocket files fail to be processed:

```
3ijh_mutate2_pocket:B:ALA100C:C and 3ijh_mutate2_pocket:B:ALA100C:C have the same coordinates
Traceback (most recent call last):
  File "/data2/rjli/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/AutoDockTools/Utilities24/prepare_receptor4.py", line 216, in <module>
    dict=dictionary)    
  File "/data2/rjli/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/AutoDockTools/MoleculePreparation.py", line 558, in __init__
    version=version, delete_single_nonstd_residues=delete_single_nonstd_residues)
  File "/data2/rjli/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/AutoDockTools/MoleculePreparation.py", line 124, in __init__
    self.repairMol(mol, self.repair_type_list)
  File "/data2/rjli/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/AutoDockTools/MoleculePreparation.py", line 174, in repairMol
    self.newHs = self.addHydrogens(mol)
  File "/data2/rjli/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/AutoDockTools/MoleculePreparation.py", line 187, in addHydrogens
    HB.addHydrogens(mol)
  File "/data2/rjli/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/MolKit/hydrogenBuilder.py", line 61, in addHydrogens
    babel.assignHybridization(mol.allAtoms)
  File "/data2/rjli/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/PyBabel/atomTypes.py", line 137, in assignHybridization
    self.valence_two()
  File "/data2/rjli/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/PyBabel/atomTypes.py", line 266, in valence_two
    angle1 = bond_angle(k.coords, a.coords, l.coords)
  File "/data2/rjli/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/PyBabel/util.py", line 47, in bond_angle
    raise ZeroDivisionError("Input used:", a, b, c)
ZeroDivisionError: ('Input used:', [-0.504, -7.572, -3.867], [-0.004, -7.796, -2.699], [-0.004, -7.796, -2.699])
```

**Comment by rwxayheee** [comment]
Hi @Kerro-junior, One possible cause for this error is there are missing atoms or distorted geometry around the questioned atom. The topology builder was having problem determining the hybridization state for the carbonyl carbon of ALA100 (which used to be a GLY..? if you haven't changed the numbering from PDB). Having distorted angle and bond lengths is common for mutant structures that are generated with in silico method. 
Hope this is mildly helpful!

**Comment by RJ-Li** [comment]
I also have questions when dealing with a pdb protein file(pdbid: 5nee) into pdbqt using ADFR.

`$ /ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/bin/prepare_receptor -r 5nee_pocket.pdb -A hydrogens -o 5nee_pocket.pdbqt
Traceback (most recent call last):
  File "/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/AutoDockTools/Utilities24/prepare_receptor4.py", line 216, in <module>
    dict=dictionary)    
  File "/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/AutoDockTools/MoleculePreparation.py", line 558, in __init__
    version=version, delete_single_nonstd_residues=delete_single_nonstd_residues)
  File "/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/AutoDockTools/MoleculePreparation.py", line 124, in __init__
    self.repairMol(mol, self.repair_type_list)
  File "/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/AutoDockTools/MoleculePreparation.py", line 174, in repairMol
    self.newHs = self.addHydrogens(mol)
  File "/data2/rjli/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/AutoDockTools/MoleculePreparation.py", line 187, in addHydrogens
    HB.addHydrogens(mol)
  File "/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/MolKit/hydrogenBuilder.py", line 81, in addHydrogens
    hat = AddHydrogens().addHydrogens(mol.allAtoms, method=self.method)
  File "/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/PyBabel/addh.py", line 92, in addHydrogens
    Hatoms = self.place_hydrogens1(atoms, num_H_to_add)
  File "/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/PyBabel/addh.py", line 156, in place_hydrogens1
    Hat = Hat + self.add_vinyl_hydrogens(a ,SP2_C_H_DIST)
  File "/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/PyBabel/addh.py", line 444, in add_vinyl_hydrogens
    c3 = c2.bonds[1].atom1
  File "/data2/rjli/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/lib/python2.7/UserList.py", line 31, in __getitem__
    def __getitem__(self, i): return self.data[i]
IndexError: list index out of range
`

**Comment by rwxayheee** [comment]
Hi @RJ-Li, 
If your input protein structure does not contain hydrogens, preprocessing with a tool to add hydrogens, optimize the H-bonding network, residue orientation and protonation states might be useful. Please consider the following programs: 
molprobity: http://molprobity.biochem.duke.edu/
APBS: https://server.poissonboltzmann.org/
H++: http://newbiophysics.cs.vt.edu/H++/

Attached is a processed PDB file for 5NEE: 
[5neeH.pdb.txt](https://github.com/ccsb-scripps/AutoDock-Vina/files/12718335/5neeH.pdb.txt)
I was able to use it as an input for prepare_receptor, without the -A option. Here is the generated PDBQT file: 
[5neeH.pdbqt.txt](https://github.com/ccsb-scripps/AutoDock-Vina/files/12718362/5neeH.pdbqt.txt)
With that, you may continue the [AutoDockZn](https://autodock-vina.readthedocs.io/en/latest/docking_zinc.html) tutorial.

**Comment by Kerro-junior** [comment]
Thanks for your advise, but I wonder why ADFR -A "hydrogens" is not good to use? 

I encountered error like the following information when processing the `*_protein.pdb without any waters or non-polar H, but with ions`.

```
File "/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/AutoDockTools/MoleculePreparation.py", line 174, in repairMol
    self.newHs = self.addHydrogens(mol)
  File "/data2/rjli/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/AutoDockTools/MoleculePreparation.py", line 187, in addHydrogens
    HB.addHydrogens(mol)
  File "/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/MolKit/hydrogenBuilder.py", line 61, in addHydrogens
    babel.assignHybridization(mol.allAtoms)
  File "/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/PyBabel/atomTypes.py", line 136, in assignHybridization
    self.valence_three()
  File "/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/PyBabel/atomTypes.py", line 236, in valence_three
    elif self.count_free_ox(a) >= 2: a.babel_type="Cac"
  File "/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/PyBabel/atomTypes.py", line 167, in count_free_ox
    self.count_heavy_atoms(bonded_atom) == 1:
  File "/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/PyBabel/atomTypes.py", line 157, in count_heavy_atoms
    if bonded_atom.babel_type[0] == 'H': count = count + 1
  File "/ADFRsuite-1.0/ADFRsuite_x86_64Linux_1.0/CCSBpckgs/MolKit/molecule.py", line 409, in __getattr__
    raise AttributeError('member %s not found'%member)
```

I'd like to use pymol, obabel or rdkit to add  non-polar Hydrogens for a batch of pdbfile, is that possible? Because it takes time to install and learn MOLprobity. Thanks!

**Comment by rwxayheee** [comment]
Hi @Kerro-junior, 
`I wonder why ADFR -A "hydrogens" is not good to use?`
Your task is out of the scope for which the application was developed for. 

`I'd like to use pymol, obabel or rdkit to add non-polar Hydrogens for a batch of pdbfile`
In my opinion, you need external packages or your own codes to support the command-line preparation of metalloproteins. If you are pursuing such systems, it is your commitment to figure out the protocol. Trying out different tools will definitely help you learn and realize the limitations of each of them. 

If you are interested, python package MDAnalysis has some well-documented topology modules. With custom residues and atoms, you might be able to generate the correct topology for your systems: 
https://docs.mdanalysis.org/stable/documentation_pages/topology_modules.html
And it has some back/forward compatibilities with RDKit objects.

**Comment by rwxayheee** [comment]
Closing as resolved
