### ISSUE TITLE
Fail when installing vina from pypi.org

### ISSUE THREAD

**Issue by BuiQuocDung1991** [ccsb-scripps/AutoDock-Vina#247]
Hi everyone
I am trying to install vina by the doc: 
https://pypi.org/project/vina/
This is my code in anaconda:

```
conda create -n vina python=3 -y
conda activate vina
conda install -c conda-forge numpy swig boost-cpp sphinx sphinx_rtd_theme -y
conda install -c anaconda git -y
git clone https://github.com/ccsb-scripps/AutoDock-Vina
cd AutoDock-Vina/build/python
python setup.py build install
```

But i got some errors below:

`Version found 1.2.5 (from __init__.py)
running build
running build_ext
Boost library is not installed in this conda environment.
Traceback (most recent call last):
  File "C:\Users\Admin\AutoDock-Vina\build\python\setup.py", line 294, in <module>
    setup(
  File "E:\Software\Anaconda3\envs\vina\Lib\site-packages\setuptools\__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Software\Anaconda3\envs\vina\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "E:\Software\Anaconda3\envs\vina\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
    dist.run_commands()
  File "E:\Software\Anaconda3\envs\vina\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "E:\Software\Anaconda3\envs\vina\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "E:\Software\Anaconda3\envs\vina\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
    cmd_obj.run()
  File "C:\Users\Admin\AutoDock-Vina\build\python\setup.py", line 149, in run
    self.run_command('build_ext')
  File "E:\Software\Anaconda3\envs\vina\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
    self.distribution.run_command(command)
  File "E:\Software\Anaconda3\envs\vina\Lib\site-packages\setuptools\dist.py", line 1234, in run_command
    super().run_command(command)
  File "E:\Software\Anaconda3\envs\vina\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
    cmd_obj.ensure_finalized()
  File "E:\Software\Anaconda3\envs\vina\Lib\site-packages\setuptools\_distutils\cmd.py", line 111, in ensure_finalized
    self.finalize_options()
  File "C:\Users\Admin\AutoDock-Vina\build\python\setup.py", line 200, in finalize_options
    raise ValueError(error_msg)
ValueError: Boost library location was not found!
Directories searched: conda env, /usr/local/include and /usr/include.`

How can i handle it?

**Comment by sherryliu987** [comment]
If you're struggling use AutoDock locally, feel free to try https://www.tamarind.bio/autodock-vina, a website which offers a no-code interface for bioinformatics tools including AutoDock for free.

**Comment by rwxayheee** [comment]
This was a pip install problem (reported in other issues). Added to Maintenance Release.
