### ISSUE TITLE
an error with pip install vina

### ISSUE THREAD

**Issue by tomlongcool** [ccsb-scripps/AutoDock-Vina#260]
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting vina
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/75/b2/1dad979aea28fcca8aa06832744aa1b62ab80cad08980115a580a4861b8d/vina-1.2.5.tar.gz (89 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      Version found 1.2.5 (from __init__.py)
      running egg_info
      creating vina.egg-info
      writing vina.egg-info\PKG-INFO
      writing dependency_links to vina.egg-info\dependency_links.txt
      writing requirements to vina.egg-info\requires.txt
      writing top-level names to vina.egg-info\top_level.txt
      writing manifest file 'vina.egg-info\SOURCES.txt'
      Boost library is not installed in this conda environment.
      Traceback (most recent call last):
        File "C:\Users\zhaol\.conda\envs\jupyter_dock\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\zhaol\.conda\envs\jupyter_dock\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\zhaol\.conda\envs\jupyter_dock\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\zhaol\AppData\Local\Temp\pip-build-env-dkc_93fy\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\zhaol\AppData\Local\Temp\pip-build-env-dkc_93fy\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\zhaol\AppData\Local\Temp\pip-build-env-dkc_93fy\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 346, in <module>
        File "C:\Users\zhaol\AppData\Local\Temp\pip-build-env-dkc_93fy\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\zhaol\AppData\Local\Temp\pip-build-env-dkc_93fy\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\zhaol\AppData\Local\Temp\pip-build-env-dkc_93fy\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\zhaol\AppData\Local\Temp\pip-build-env-dkc_93fy\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\zhaol\AppData\Local\Temp\pip-build-env-dkc_93fy\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\zhaol\AppData\Local\Temp\pip-build-env-dkc_93fy\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\zhaol\AppData\Local\Temp\pip-build-env-dkc_93fy\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 321, in run
          self.find_sources()
        File "C:\Users\zhaol\AppData\Local\Temp\pip-build-env-dkc_93fy\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
          mm.run()
        File "C:\Users\zhaol\AppData\Local\Temp\pip-build-env-dkc_93fy\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 551, in run
          self.add_defaults()
        File "C:\Users\zhaol\AppData\Local\Temp\pip-build-env-dkc_93fy\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\zhaol\AppData\Local\Temp\pip-build-env-dkc_93fy\overlay\Lib\site-packages\setuptools\command\sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "C:\Users\zhaol\AppData\Local\Temp\pip-build-env-dkc_93fy\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\zhaol\AppData\Local\Temp\pip-build-env-dkc_93fy\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 335, in _add_defaults_ext
          build_ext = self.get_finalized_command('build_ext')
        File "C:\Users\zhaol\AppData\Local\Temp\pip-build-env-dkc_93fy\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 305, in get_finalized_command
          cmd_obj.ensure_finalized()
        File "C:\Users\zhaol\AppData\Local\Temp\pip-build-env-dkc_93fy\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 111, in ensure_finalized
          self.finalize_options()
        File "<string>", line 247, in finalize_options
      ValueError: Boost library location was not found!
      Directories searched: conda env, /usr/local/include and /usr/include.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by Solarrixs** [comment]
I have the same error

**Comment by diogomart** [comment]
The error message says that boost is missing. One way to install it is with conda or mamba or micromamba

**Comment by Solarrixs** [comment]
Yes, I have installed boost. brew install boost. I simlinked it into the correct path as well.

**Comment by diogomart** [comment]
I see. The error is still there though. We have not gotten python bindings to work on windows, so maybe it's something else. Sorry, cant help much.

**Comment by rwxayheee** [comment]
pip install problem. Added to Maintenance Release for future reference.
