### ISSUE TITLE
prepare_receptor causes `ValueError: Could not find atomic number for Hn Hn` 

### ISSUE THREAD

**Issue by eunos-1128** [ccsb-scripps/AutoDock-Vina#283]
I tried to validate the accuracy of Vina on the DUD-E dataset according to the AutoDock Vina v1.2.0 paper and the supporting information description.

After adding hydrogens to the receptor of the DUD-E co-crystal structure using `reduce` (with the option to flip NQH groups), I tried to prepare PDBQT files with `prepare_receptor` in ADFRsuite as below.

```bash
for prot_name in *; do
    reduce -FLIP "./${prot_name}/receptor.pdb" > proteins/DUD-E/${prot_name}-FHs.pdb
done
```

```bash
for prot_name in *; do
    prepare_receptor \
    -r proteins/DUD-E/${prot_name}-FHs.pdb \
    -o dockings/vina/data/DUD-E/receptors/${prot_name}-FHs.pdbqt
done
```

In result the following error occurred.

```log
adding gasteiger charges to peptide
Traceback (most recent call last):
  File "/home/uenom/data_ueno/dockings/ADFRsuite-1.1dev/ADFRsuite_x86_64Linux_1.1dev/ADFRsuite-1.1dev/CCSBpckgs/AutoDockTools/Utilities24/prepare_receptor4.py", line 216, in <module>
    dict=dictionary)    
  File "/home/uenom/data_ueno/dockings/ADFRsuite-1.1dev/ADFRsuite_x86_64Linux_1.1dev/ADFRsuite-1.1dev/CCSBpckgs/AutoDockTools/MoleculePreparation.py", line 558, in __init__
    version=version, delete_single_nonstd_residues=delete_single_nonstd_residues)
  File "/home/uenom/data_ueno/dockings/ADFRsuite-1.1dev/ADFRsuite_x86_64Linux_1.1dev/ADFRsuite-1.1dev/CCSBpckgs/AutoDockTools/MoleculePreparation.py", line 141, in __init__
    self.addCharges(mol, charges_to_add)
  File "/home/uenom/data_ueno/dockings/ADFRsuite-1.1dev/ADFRsuite_x86_64Linux_1.1dev/ADFRsuite-1.1dev/CCSBpckgs/AutoDockTools/MoleculePreparation.py", line 227, in addCharges
    chargeCalculator.addCharges(mol.allAtoms)
  File "/home/uenom/data_ueno/dockings/ADFRsuite-1.1dev/ADFRsuite_x86_64Linux_1.1dev/ADFRsuite-1.1dev/CCSBpckgs/MolKit/chargeCalculator.py", line 80, in addCharges
    babel.assignHybridization(atoms)
  File "/home/uenom/data_ueno/dockings/ADFRsuite-1.1dev/ADFRsuite_x86_64Linux_1.1dev/ADFRsuite-1.1dev/CCSBpckgs/PyBabel/atomTypes.py", line 127, in assignHybridization
    a.babel_atomic_number = self.get_atomic_number(a.babel_type)
  File "/home/uenom/data_ueno/dockings/ADFRsuite-1.1dev/ADFRsuite_x86_64Linux_1.1dev/ADFRsuite-1.1dev/CCSBpckgs/PyBabel/atomTypes.py", line 103, in get_atomic_number
    (name,_name) )
ValueError: Could not find atomic number for Hn Hn
```

Is this due to software bugs or incorrect tool usage?

Any advice would be appreciated!

**Comment by eunos-1128** [comment]
No element information corresponding to each atom in cocrystal receptor's PDB data in DUD-E dataset was provided.

That caused this error. When running prepare_receptor, the program bundled in it seems not to work for PDB data which don't have each atom's element description.

I repaired PDB data and ran prepare_receptor successfully.

**Comment by longyuxi** [comment]
Hello @eunos-1128, would you mind posting how you repaired the PDB data? Did you change each "HN" to "H", or something else?

Thanks in advance.

**Comment by eunos-1128** [comment]
@longyuxi 

I used the script below to correct HNZ in LYS residue assigned to `"X"`.

```python

#!/usr/bin/env python3

import argparse
import os
import re
import sys

from Bio.PDB import PDBIO, PDBParser
from Bio.Data import IUPACData


NON_METAL_ELEMS = {"H", "D", "C", "N", "O", "F", "P", "S", "Br", "I"}

metal_elems = set(IUPACData.atom_weights.keys()) - NON_METAL_ELEMS

# Parse command line arguments
parser = argparse.ArgumentParser()
parser.add_argument("--input", help="Input PDB file", type=str)
args = parser.parse_args()

# Read the PDB file
pdb_parser = PDBParser(QUIET=True)
filepath = args.input
filename = os.path.basename(filepath)
stem, ext = os.path.splitext(filename)
structure = pdb_parser.get_structure(stem, args.input)

for model in structure.get_models():
    for chain in model.get_chains():
        for residue in chain.get_residues():
            for atom in residue.get_atoms():
                # Use Biopython's method to assign element names
                atom.element = atom._assign_element(atom.element)
                atom_fullname = atom.fullname.strip()

                # Fix `"X"` elements which cause an error in the later `prepare_receptor` process
                if atom.element == "X":

                    # HNZ in LYS residue is incorrectly assigned `"X"` due to a Biopython bug
                    pattern = re.compile(r"^HN[A-Z]\d$")
                    if pattern.match(atom_fullname):
                        atom.element = "H"

                    # Treat all metal atoms as divalent cations
                    elif atom_fullname.capitalize() in metal_elems:
                        atom.element = atom_fullname.upper()
                        atom.pqr_charge = 2

# Output the corrected PDB file to standard output
pdb_io = PDBIO()
pdb_io.set_structure(structure)
pdb_io.save(sys.stdout)

```

**Comment by longyuxi** [comment]
@eunos-1128 Thank you!
