### ISSUE TITLE
Error in Preparing the ligand for hydrated docking tutorial example

### ISSUE THREAD

**Issue by romanchemist** [ccsb-scripps/AutoDock-Vina#64]
When I do mk_prepare_ligand.py -i 1uw6_ligand.sdf -o 1uw6_ligand.pdbqt --pH 7.4 -w 
I get -> RuntimeError: Cannot place water molecules on atom 7 of type NA with 4 neighbors.
It's error in code and if to add this key 4: (1, 3) in self._hb_config for key 'NA', it also have some problems (adding one extra water, for example: 5 water for protonated ammonia where 2 molecules of water have equal coordinates). For nicotine it's the same.
If it's possible, please check and fix it.  Thanks!

**Comment by diogomart** [comment]
Thank you for reporting this. I can reproduce on my end, will post here when fixed.

**Comment by jasonlse** [comment]
Hi, I had the same issue. But when I install the fixed version from source I get the following error instead:

> Traceback (most recent call last): 
  File "/opt/miniconda3/envs/vina/bin/mk_prepare_ligand.py", line 173, in <module>
    ligand_prepared = preparator.write_pdbqt_string()
  File "/opt/miniconda3/envs/vina/lib/python3.9/site-packages/meeko/preparation.py", line 208, in write_pdbqt_string
    return self._writer.write_string(self.setup, remove_index_map, remove_smiles)
  File "/opt/miniconda3/envs/vina/lib/python3.9/site-packages/meeko/writer.py", line 142, in write_string
    self._walk_graph_recursive(root, first=True)
  File "/opt/miniconda3/envs/vina/lib/python3.9/site-packages/meeko/writer.py", line 82, in _walk_graph_recursive
    self._pdbqt_buffer.append(self._make_pdbqt_line(member))
  File "/opt/miniconda3/envs/vina/lib/python3.9/site-packages/meeko/writer.py", line 54, in _make_pdbqt_line
    atom_symbol = mini_periodic_table[atomic_num]
KeyError: 0

Is there still an error in the code or am I doing something wrong?

**Comment by diogomart** [comment]
Fixed in 7e2574838a4ed38984dcd41878b236485477af22
Thanks for finding it and posting here :)

**Comment by jasonlse** [comment]
Yup, seems to work now. Cheers.
