### ISSUE TITLE
Is ADFR available for new Mac SOCs?

### ISSUE THREAD

**Issue by tanzibin108** [ccsb-scripps/AutoDock-Vina#65]
Hi there,
I have a Mac with M1 Pro and a Windows PC. Tried to install vina on Windows but the installation failed. 
Then tried to install vina on Mac and successfully installed vina with Python 3.7.
Vina executable is working for 1.1.2 but not for 1.2.3
Tried installing ADFR, but it errored out when running the .py

`
(base) tanzibin@ZibinsMacBookPro vina % prepare_receptor -r 1iep_receptorH.pdb -o 1iep_receptor.pdbqt
Traceback (most recent call last):
  File "/Users/tanzibin/ADFR/CCSBpckgs/AutoDockTools/Utilities24/prepare_receptor4.py", line 150, in <module>
    mol = mols[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
`

`(base) tanzibin@ZibinsMacBookPro vina % conda activate vina
(vina) tanzibin@ZibinsMacBookPro vina % mk_prepare_ligand.py -i 1iep_ligand.sdf -o 1iep_ligand.pdbqt --pH 7.4
Traceback (most recent call last):
  File "/Users/tanzibin/opt/anaconda3/envs/vina/bin/mk_prepare_ligand.py", line 13, in <module>
    from meeko import MoleculePreparation
  File "/Users/tanzibin/opt/anaconda3/envs/vina/lib/python3.7/site-packages/meeko/__init__.py", line 7, in <module>
    from .preparation import MoleculePreparation
  File "/Users/tanzibin/opt/anaconda3/envs/vina/lib/python3.7/site-packages/meeko/preparation.py", line 19, in <module>
    from .writer import PDBQTWriterLegacy
  File "/Users/tanzibin/opt/anaconda3/envs/vina/lib/python3.7/site-packages/meeko/writer.py", line 12, in <module>
    from rdkit import Chem
ModuleNotFoundError: No module named 'rdkit'
`

Any idea?

Thanks

**Comment by diogomart** [comment]
Hi,

The error you posted is from a Meeko script, not ADFR. You can install the missing dependency (rdkit) with anaconda or miniconda: https://anaconda.org/conda-forge/rdkit
