### ISSUE TITLE
Error when try install with pip command

### ISSUE THREAD

**Issue by deeplearchem** [ccsb-scripps/AutoDock-Vina#85]
Hi, I'm trying to install Vina but when I use the command `pip install -U numpy vina` I get this, but I can´t understand the error:

```
Collecting vina
  Using cached vina-1.2.3.tar.gz (95 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.18 in c:\users\familia\.conda\envs\vina\lib\site-packages (from vina) (1.22.2)
Building wheels for collected packages: vina
  Building wheel for vina (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for vina (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [56 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Version found 1.2.3 (from __init__.py)
      running bdist_wheel
      running build
      running build_ext
      Boost library location automatically determined in this conda environment.
      Boost library location was automatically guessed at C:\Users\Familia\.conda\envs\vina\include.
      - include_dirs: ['C:\\Users\\Familia\\.conda\\envs\\vina\\include', 'C:\\Users\\Familia\\.conda\\envs\\vina\\Include', 'C:\\Users\\Familia\\.conda\\envs\\vina\\include', 'src/lib']
      - library_dirs: ['C:\\Users\\Familia\\.conda\\envs\\vina\\libs', 'C:\\Users\\Familia\\.conda\\envs\\vina', 'C:\\Users\\Familia\\.conda\\envs\\vina\\PCbuild\\amd64', 'C:\\Users\\Familia\\.conda\\envs\\vina\\lib']
      - swig options: ['-c++', '-small', '-naturalvar', '-fastdispatch', '-shadow', '-py3', '-IC:\\Users\\Familia\\.conda\\envs\\vina\\include', '-IC:\\Users\\Familia\\.conda\\envs\\vina\\Include', '-IC:\\Users\\Familia\\.conda\\envs\\vina\\include', '-Isrc/lib']
      - libraries: []
      - extra link args: ['-lboost_thread', '-lboost_serialization', '-lboost_filesystem', '-lboost_program_options']
      Traceback (most recent call last):
        File "C:\Users\Familia\.conda\envs\vina\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\Familia\.conda\envs\vina\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Familia\.conda\envs\vina\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 261, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\Familia\AppData\Local\Temp\pip-build-env-pgn2x7bd\overlay\Lib\site-packages\setuptools\build_meta.py", line 229, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
        File "C:\Users\Familia\AppData\Local\Temp\pip-build-env-pgn2x7bd\overlay\Lib\site-packages\setuptools\build_meta.py", line 214, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\Familia\AppData\Local\Temp\pip-build-env-pgn2x7bd\overlay\Lib\site-packages\setuptools\build_meta.py", line 157, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 346, in <module>
          setup(
        File "C:\Users\Familia\AppData\Local\Temp\pip-build-env-pgn2x7bd\overlay\Lib\site-packages\setuptools\__init__.py", line 155, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Familia\AppData\Local\Temp\pip-build-env-pgn2x7bd\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 148, in setup
          return run_commands(dist)
        File "C:\Users\Familia\AppData\Local\Temp\pip-build-env-pgn2x7bd\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 163, in run_commands
          dist.run_commands()
        File "C:\Users\Familia\AppData\Local\Temp\pip-build-env-pgn2x7bd\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "C:\Users\Familia\AppData\Local\Temp\pip-build-env-pgn2x7bd\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\Familia\AppData\Local\Temp\pip-build-env-pgn2x7bd\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "C:\Users\Familia\AppData\Local\Temp\pip-build-env-pgn2x7bd\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Familia\AppData\Local\Temp\pip-build-env-pgn2x7bd\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "setup.py", line 196, in run
          self.run_command('build_ext')
        File "C:\Users\Familia\AppData\Local\Temp\pip-build-env-pgn2x7bd\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Familia\AppData\Local\Temp\pip-build-env-pgn2x7bd\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 986, in run_command
          cmd_obj.run()
        File "C:\Users\Familia\AppData\Local\Temp\pip-build-env-pgn2x7bd\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 79, in run
          _build_ext.run(self)
        File "C:\Users\Familia\AppData\Local\Temp\pip-build-env-pgn2x7bd\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
          self.build_extensions()
        File "setup.py", line 301, in build_extensions
          self.compiler.compiler_so[0] = "g++"
      AttributeError: 'MSVCCompiler' object has no attribute 'compiler_so'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vina
Failed to build vina
ERROR: Could not build wheels for vina, which is required to install pyproject.toml-based projects
```
Already I trying to change the python version of the environment to 3.8, 3.9 and 3.7 but I get the same error

**Comment by sherryliu987** [comment]
If you're struggling use AutoDock locally, feel free to try https://www.tamarind.bio/, a website which offers a no-code interface for bioinformatics tools including AutoDock for free.

**Comment by hrp1000** [comment]
This is still an issue with version 1.2.5 and Python 3.11.7 - trying to install on a Linux node - CentOS Linux release 7.9.2009 (Core)

**Comment by rwxayheee** [comment]
Added to Maintenance Release: The original error might be stale. But as of today, it's an existing issue that `pip install` is not working.

**Comment by joanimato** [comment]
This has been addressed with release 1.2.7. It should work up to python version 3.12. 

Closing this for now, let us know if you're still having problems.
